#!/bin/bash
#PBS -l nodes=1:ppn=1:gpus=1:titan
#PBS -l walltime=00:30:00
#PBS -l mem=18GB

module purge
module load cuda/6.5.12
RESULTS=results
TORCHDIR=/scratch/courses/DSGA1008/bin
export PATH=$PATH:$TORCHDIR
cd $HERE
th doall.lua -type cuda -trteb 2 -size full -kaggle kaggle.csv -save $RESULTS
#sed -i 's/\([0-9][0-9]*\),\([0-9][0-9]*\)/\1 , \2/' $RESULTS/kaggle.csv
