#!/bin/bash
#PBS -l nodes=1:ppn=1:gpus=1:titan
#PBS -l walltime=01:00:00
#PBS -l mem=18GB

module purge
module load cuda/6.5.12
RESULTS=results
TORCHDIR=/scratch/courses/DSGA1008/bin
DATADIR=/scratch/courses/DSGA1008/A2/binary
NAME=MonkeyBusiness
RESULTS=results
export PATH=$PATH:$TORCHDIR
RUNDIR=$HERE/$NAME-${PBS_JOBID/.*}/stl10_binary
mkdir -p $RUNDIR
cd $RUNDIR
cp -rs $DATADIR/* ./
cd ..
cp  $HERE/*.lua ./
th doall.lua -type cuda -size full -models 1 -loss nll -save $RESULTS -maxtime 80 -modelName combined_model.net
