#!/bin/bash
#PBS -l nodes=1:ppn=1:gpus=1:titan
#PBS -l walltime=00:10:00
#PBS -l mem=8GB
#Run this file in the directory where the combined_model.net is and where all of the .lua files used are.

module purge
module load cuda/6.5.12
RESULTS=results
TORCHDIR=/scratch/courses/DSGA1008/bin
DATADIR=/scratch/courses/DSGA1008/A2/binary
NAME=testResults
export PATH=$PATH:$TORCHDIR
RUNDIR=$HERE/$NAME-${PBS_JOBID/.*}/stl10_binary
mkdir -p $RUNDIR
cd $RUNDIR
cp -rs $DATADIR/* ./
cd ..
cp  $HERE/*.lua ./
cp -s $HERE/*.net ./
th doall.lua -type cuda -size notdebug -trteb 2 -modelName combined_model.net -kaggle kaggle.csv
